### ISSUE TITLE
Imminent removal of Windows runner used by "build" workflow

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-language-server#107]
### Current behavior

This repository contains a GitHub Actions workflow which builds the Arduino Language Server to provide a "smoke test" and facilitate testing of pull requests and to produce nightly builds:

https://github.com/arduino/arduino-language-server/blob/main/.github/workflows/build.yml

This workflow runs jobs on Linux, macOS, and Windows machines ("runners").

The Windows runner version used is `windows-2016`. GitHub plans to remove this version on 2022-06-30:

https://github.com/actions/virtual-environments/issues/5403

They are also performing intentional brownouts of the runner to encourage migration to the newer runner versions.

The original removal date was 2022-04-01 (https://github.com/actions/virtual-environments/issues/4312). Despite the claim of a respite, none of the workflow runs since that time have passed:

https://github.com/arduino/arduino-language-server/actions/workflows/build.yml?query=is%3Asuccess

### Expected behavior

"build" workflow uses a reliable Windows runner version.

**Comment by Ziya137200** [comment]
> ## Bug Report
> ### Current behavior
> This repository contains a GitHub Actions workflow which builds the Arduino Language Server to provide a "smoke test" and facilitate testing of pull requests and to produce nightly builds:
> 
> https://github.com/arduino/arduino-language-server/blob/main/.github/workflows/build.yml
> 
> This workflow runs jobs on Linux, macOS, and Windows machines ("runners").
> 
> The Windows runner version used is `windows-2016`. GitHub plans to remove this version on 2022-06-30:
> 
> [actions/virtual-environments#5403](https://github.com/actions/virtual-environments/issues/5403)
> 
> They are also performing intentional brownouts of the runner to encourage migration to the newer runner versions.
> 
> The original removal date was 2022-04-01 ([actions/virtual-environments#4312](https://github.com/actions/virtual-environments/issues/4312)). Despite the claim of a respite, none of the workflow runs since that time have passed:
> 
> https://github.com/arduino/arduino-language-server/actions/workflows/build.yml?query=is%3Asuccess
> 
> ### Expected behavior
> "build" workflow uses a reliable Windows runner version.
