### ISSUE TITLE
add version as ldflag

### ISSUE THREAD

**Issue by umbynos** [arduino/arduino-language-server#137]
currently during the release we have to manually set the version in https://github.com/arduino/arduino-language-server/blob/6aec1ed0cf7d60d7b5c6409cc318bad20e17e833/ls/ls.go#L359 This can be enhanced like we do in the Arduino CLI: https://github.com/arduino/arduino-cli/blob/master/Taskfile.yml#L351

**Comment by MatteoPologruto** [comment]
Done here: https://github.com/arduino/arduino-language-server/pull/139
