### ISSUE TITLE
setting cli-config after build not terminating

### ISSUE THREAD

**Issue by husseljoo** [arduino/arduino-language-server#91]
### Current behavior
After cloning the repo in /usr/lib/go/src and running 
go build
And then going over to /usr/lib/go/bin 
./arduino-language-server -cli-config $HOME/.arduino15/arduino-cli.yaml
this command takes forever to run and does not seem to teriminate I have left it for 4 hrs.

### Environment
- Language Server version (commit hash): 08181a151ede4565aae0991ab0e81aafac58887d
- CLI version used (output of `arduino-cli version`): arduino-cli alpha Version: 0.19.3-arch Commit: 12f1afc2c1dee08d988974fe8f80e849f7ce4681
- OS and platform: Arch-Linux

**Comment by per1234** [comment]
Duplicates https://github.com/arduino/arduino-language-server/issues/84
